-- KORAVERSE 5 · additive migration from 4.1. Run after existing migrations.
begin;
alter table public.koraverse_messages add column if not exists client_id uuid;
create unique index if not exists koraverse_message_client_id on public.koraverse_messages(client_id) where client_id is not null;

create table if not exists public.koraverse_presence (
  session_id uuid primary key,
  player_key text not null,
  name text not null,
  avatar_id text not null default 'cow-classic',
  screen text,
  current_world text,
  status text not null default 'online' check (status in ('online','idle','offline')),
  last_seen timestamptz not null default now(),
  last_activity timestamptz not null default now()
);
create index if not exists koraverse_presence_recent on public.koraverse_presence(last_seen desc);
alter table public.koraverse_presence enable row level security;
do $$ begin
create policy koraverse_presence_read on public.koraverse_presence for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
create policy koraverse_presence_insert on public.koraverse_presence for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
create policy koraverse_presence_update on public.koraverse_presence for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
grant select,insert,update on public.koraverse_presence to anon;

create table if not exists public.koraverse_constellations (
  id bigint generated by default as identity primary key,
  player_key text not null,
  event_key text not null,
  label text not null,
  icon text not null default '✦',
  created_at timestamptz not null default now(),
  unique(player_key,event_key)
);
alter table public.koraverse_constellations enable row level security;
do $$ begin
create policy koraverse_constellations_read on public.koraverse_constellations for select to anon using (true);
exception when duplicate_object then null; end $$;
do $$ begin
create policy koraverse_constellations_insert on public.koraverse_constellations for insert to anon with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
create policy koraverse_constellations_update on public.koraverse_constellations for update to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
grant select,insert,update on public.koraverse_constellations to anon;
grant usage,select on sequence public.koraverse_constellations_id_seq to anon;
grant select,insert on public.koraverse_messages to anon;
grant usage,select on sequence public.koraverse_messages_id_seq to anon;

-- Admin membership can only be assigned from SQL Editor / service role.
create table if not exists public.koraverse_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
alter table public.koraverse_admins enable row level security;
revoke all on public.koraverse_admins from anon,authenticated;
create or replace function public.koraverse_is_admin()
returns boolean language sql stable security definer
set search_path = ''
as $$ select exists(select 1 from public.koraverse_admins where user_id = auth.uid()); $$;
revoke all on function public.koraverse_is_admin() from public,anon;
grant execute on function public.koraverse_is_admin() to authenticated;

-- INSERT delivery requires membership in the Realtime publication.
do $$ begin
if not exists(select 1 from pg_publication where pubname='supabase_realtime') then
  create publication supabase_realtime;
end if;
if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='koraverse_messages') then
  alter publication supabase_realtime add table public.koraverse_messages;
end if;
end $$;
commit;

-- One-time admin enrollment (replace with YOUR Supabase Auth user UUID):
-- insert into public.koraverse_admins(user_id) values ('YOUR-USER-UUID') on conflict do nothing;
-- Optional maintenance, after reviewing retention: remove presence rows older than 30 days.
