-- KORAVERSE 4.0 — Premium Social Core
-- Ejecuta este archivo UNA VEZ después del schema de KORAVERSE 3.0.

alter table public.koraverse_profiles
  add column if not exists trivia_xp integer not null default 0,
  add column if not exists avatar_id text not null default 'cow-classic',
  add column if not exists status_message text,
  add column if not exists last_seen timestamptz;

create table if not exists public.koraverse_messages (
  id bigint generated by default as identity primary key,
  from_player text not null,
  to_player text not null,
  body text not null,
  kind text not null default 'text',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.koraverse_messages enable row level security;

do $$ begin
  create policy "koraverse_messages_all" on public.koraverse_messages
  for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;

create index if not exists idx_koraverse_messages_pair_time
  on public.koraverse_messages(from_player, to_player, created_at desc);
create index if not exists idx_koraverse_messages_target_time
  on public.koraverse_messages(to_player, created_at desc);
