-- KORAVERSE 3.0 — esquema persistente.
-- Ejecuta TODO este archivo en Supabase > SQL Editor una sola vez.

create table if not exists public.koraverse_profiles (
  player_key text primary key,
  display_name text not null,
  xp integer not null default 0,
  english_xp integer not null default 0,
  puzzle_xp integer not null default 0,
  arcade_xp integer not null default 0,
  duo_xp integer not null default 0,
  streak integer not null default 0,
  last_active date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.koraverse_activity (
  id bigint generated by default as identity primary key,
  player_key text not null,
  category text not null,
  source text not null,
  xp integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.koraverse_duo (
  id integer primary key default 1 check (id = 1),
  xp integer not null default 0,
  sessions integer not null default 0,
  garden_level integer not null default 1,
  updated_at timestamptz not null default now()
);
insert into public.koraverse_duo(id) values (1) on conflict (id) do nothing;

create table if not exists public.koraverse_signals (
  id bigint generated by default as identity primary key,
  from_player text not null,
  to_player text not null,
  message text not null default 'quiere jugar contigo',
  seen boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.koraverse_english_progress (
  player_key text not null,
  lesson_id text not null,
  correct integer not null default 0,
  attempts integer not null default 0,
  mastery integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(player_key, lesson_id)
);

-- Contenido opcional que puedes ampliar sin volver a desplegar el front-end.
create table if not exists public.koraverse_english_content (
  id bigint generated by default as identity primary key,
  lesson_id text not null,
  level text not null,
  topic text not null,
  kind text not null,
  prompt text not null,
  options jsonb,
  answer jsonb not null,
  explanation text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.koraverse_profiles enable row level security;
alter table public.koraverse_activity enable row level security;
alter table public.koraverse_duo enable row level security;
alter table public.koraverse_signals enable row level security;
alter table public.koraverse_english_progress enable row level security;
alter table public.koraverse_english_content enable row level security;

-- Esta app es privada por enlace y no usa autenticación de Supabase.
-- Las siguientes políticas permiten al cliente anónimo leer/escribir solo estas tablas del juego.
do $$ begin
  create policy "koraverse_profiles_all" on public.koraverse_profiles for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "koraverse_activity_all" on public.koraverse_activity for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "koraverse_duo_all" on public.koraverse_duo for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "koraverse_signals_all" on public.koraverse_signals for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "koraverse_english_progress_all" on public.koraverse_english_progress for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
do $$ begin
  create policy "koraverse_english_content_read" on public.koraverse_english_content for select to anon using (active = true);
exception when duplicate_object then null; end $$;

create index if not exists idx_koraverse_activity_player_time on public.koraverse_activity(player_key, created_at desc);
create index if not exists idx_koraverse_signals_target on public.koraverse_signals(to_player, seen, created_at desc);

-- Opcional para Push Notifications reales (KORA SIGNAL con la app cerrada).
create table if not exists public.koraverse_push_subscriptions (
  id bigint generated by default as identity primary key,
  player_key text not null,
  endpoint text not null unique,
  subscription jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.koraverse_push_subscriptions enable row level security;
-- No se crea política anon: solo las funciones server-side con service role acceden a esta tabla.
create index if not exists idx_koraverse_push_player on public.koraverse_push_subscriptions(player_key);

-- KORAVERSE 4.0 — Premium Social Core
alter table public.koraverse_profiles
  add column if not exists trivia_xp integer not null default 0,
  add column if not exists avatar_id text not null default 'cow-classic',
  add column if not exists status_message text,
  add column if not exists last_seen timestamptz;

create table if not exists public.koraverse_messages (
  id bigint generated by default as identity primary key,
  from_player text not null,
  to_player text not null,
  body text not null,
  kind text not null default 'text',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.koraverse_messages enable row level security;
do $$ begin
  create policy "koraverse_messages_all" on public.koraverse_messages for all to anon using (true) with check (true);
exception when duplicate_object then null; end $$;
create index if not exists idx_koraverse_messages_pair_time on public.koraverse_messages(from_player, to_player, created_at desc);
create index if not exists idx_koraverse_messages_target_time on public.koraverse_messages(to_player, created_at desc);
