import {createClient} from '@supabase/supabase-js'
import {MEDIA_BUCKET,validMediaPath,photoMetadata} from './signals-utils.js'
import {escapeHTML as esc} from './sky-utils.js'
export const MAX_INPUT_BYTES=20*1024*1024
export function photoDimensions(width,height,limit=1800){if(!Number.isFinite(width)||!Number.isFinite(height)||width<1||height<1||width*height>80000000)throw Error('La imagen es demasiado grande para procesarla.');const ratio=Math.min(1,limit/Math.max(width,height));return {width:Math.max(1,Math.round(width*ratio)),height:Math.max(1,Math.round(height*ratio))}}
export async function preparePhoto(file){
 if(!file||file.size<1||file.size>MAX_INPUT_BYTES)throw Error('Elige una foto de hasta 20 MB.')
 if(!['image/jpeg','image/png','image/webp','image/heic','image/heif'].includes(file.type)&&! /\.(jpe?g|png|webp|heic|heif)$/i.test(file.name||''))throw Error('Elige JPEG, PNG o WebP.')
 let bitmap
 try{bitmap=await createImageBitmap(file,{imageOrientation:'from-image'})}catch{throw Error('Este navegador no pudo abrir la foto. Convierte HEIC a JPEG o WebP.')}
 try{
  const size=photoDimensions(bitmap.width,bitmap.height)
  async function encode(limit){const d=photoDimensions(bitmap.width,bitmap.height,limit),canvas=document.createElement('canvas');canvas.width=d.width;canvas.height=d.height;const ctx=canvas.getContext('2d');ctx.drawImage(bitmap,0,0,d.width,d.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));if(!blob)throw Error('No se pudo preparar la foto.');return {blob,...d}}
  const full=await encode(1800),thumb=await encode(480)
  if(!['image/webp','image/jpeg'].includes(full.blob.type)||full.blob.size>4*1024*1024)throw Error('No se pudo reducir la foto; elige una más pequeña.')
  return {...size,blob:full.blob,thumbnail:thumb.blob,mime:full.blob.type,original_name:file.name||'photo'}
 }finally{bitmap.close()}
}
export class ChatMedia{
 constructor({url,key,player,qa=()=>false}){Object.assign(this,{url,key,player,qa});this.client=null;this.cache=new Map();this.pending=new Map()}
 getClient(){if(this.qa())throw Error('Las fotos reales están desactivadas en QA.');if(!this.url||!this.key)throw Error('Fotos no configuradas.');this.client ||= createClient(this.url,this.key,{auth:{storageKey:'koraverse_media_auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});return this.client}
 async member(){const c=this.getClient(),{data:{session}}=await c.auth.getSession();if(!session)return false;const {data,error}=await c.from('koraverse_media_members').select('player_key').eq('user_id',session.user.id).maybeSingle();return !error&&data?.player_key===this.player()}
 async authorize(){if(await this.member())return true;return new Promise(resolve=>{const el=document.createElement('dialog');el.className='media-login';el.innerHTML=`<form><h2>Fotos entre órbitas</h2><p>Entra con tu cuenta autorizada para ver y enviar fotografías. El chat de texto sigue disponible.</p><label>Email<input name="email" type="email" autocomplete="username" required></label><label>Contraseña<input name="password" type="password" autocomplete="current-password" required></label><p role="status"></p><button type="submit">Entrar</button><button type="button" class="media-cancel">Volver</button></form>`;document.body.append(el);el.showModal();const close=()=>{el.close();el.remove();resolve(false)};el.oncancel=e=>{e.preventDefault();close()};el.querySelector('.media-cancel').onclick=close;el.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=f.querySelector('[type=submit]');b.disabled=true;try{const c=this.getClient(),{error}=await c.auth.signInWithPassword({email:f.elements.email.value,password:f.elements.password.value});f.elements.password.value='';if(error||!await this.member()){await c.auth.signOut();throw Error('Esta cuenta no abre las fotos de este perfil.')}el.close();el.remove();resolve(true)}catch(error){f.querySelector('[role=status]').textContent=error.message;b.disabled=false}}})}
 async upload(prepared){if(this.qa())throw Error('QA no sube fotografías.');if(!await this.authorize())return null;const c=this.getClient(),bucket=c.storage.from(MEDIA_BUCKET),date=new Date(),stem=`${this.player()}/${date.getUTCFullYear()}/${String(date.getUTCMonth()+1).padStart(2,'0')}/${crypto.randomUUID()}`,ext=prepared.mime==='image/jpeg'?'jpg':'webp',path=`${stem}.${ext}`,thumbnail_path=`${stem}-thumb.${ext}`;const metadata=photoMetadata({...prepared,path,thumbnail_path});const {error}=await bucket.upload(path,prepared.blob,{contentType:prepared.mime,upsert:false});if(error)throw Error('No se pudo subir la fotografía.');const thumb=await bucket.upload(thumbnail_path,prepared.thumbnail,{contentType:prepared.thumbnail.type,upsert:false});if(thumb.error){await bucket.remove([path]);throw Error('No se pudo subir la miniatura.')}return metadata}
 async cleanup(metadata){if(this.qa()||!metadata)return;await this.getClient().storage.from(MEDIA_BUCKET).remove([metadata.path,metadata.thumbnail_path])}
 async signed(path){if(!validMediaPath(path)||this.qa())return null;const cached=this.cache.get(path);if(cached?.until>Date.now())return cached.url;if(this.pending.has(path))return this.pending.get(path);const request=(async()=>{if(!await this.member())return null;const {data,error}=await this.getClient().storage.from(MEDIA_BUCKET).createSignedUrl(path,900);if(error)return null;this.cache.set(path,{url:data.signedUrl,until:Date.now()+840000});return data.signedUrl})();this.pending.set(path,request);try{return await request}finally{this.pending.delete(path)}}
 async hydrate(root){if(this.qa())return;await Promise.all([...root.querySelectorAll('[data-photo-path]')].map(async img=>{const url=await this.signed(img.dataset.photoPath);if(url&&img.isConnected){img.src=url;img.parentElement.querySelector('.photo-access-note')?.setAttribute('hidden','')}}))}
 async open(message){if(!await this.authorize())return;const url=await this.signed(message.metadata?.path);if(!url)throw Error('La foto no está disponible.');openPhotoLightbox(url,message.body||'',message.metadata?.original_name)}
 async signOut(){this.cache.clear();if(this.client)await this.client.auth.signOut()}
}
export function openPhotoLightbox(url,caption='',name='photo.webp'){
 const before=document.activeElement,dialog=document.createElement('dialog');dialog.className='photo-lightbox';dialog.innerHTML=`<header><button class="photo-close" aria-label="Cerrar fotografía">×</button><label>Zoom <input type="range" min="100" max="300" value="100"></label><a href="${esc(url)}" download="${esc(name)}">Guardar fotografía</a></header><div class="photo-lightbox-scroll"><img src="${esc(url)}" alt="${esc(caption||'Fotografía compartida')}"></div><p>${esc(caption)}</p>`;document.body.append(dialog);dialog.showModal();const close=()=>{dialog.close();dialog.remove();before?.focus?.()};dialog.querySelector('.photo-close').onclick=close;dialog.oncancel=e=>{e.preventDefault();close()};dialog.querySelector('input').oninput=e=>dialog.querySelector('img').style.width=e.target.value+'%';return dialog
}
