import {mountAlignmentStory} from './alignment-story.js'
import './alignment-story.css'
import {universeEngine as engine} from './universe-engine.js'
import {BIRTHDAY,CONSTELLATIONS} from './birthday-data.js'
import {birthdayAdornment,mountAlignment,RoseGarden} from './birthday-experience.js'
import {CelestialAtlas} from './atlas.js'
import {mergeStars,legacyStar} from './sky-utils.js'
import {Sanctuary} from './sanctuary.js'
import {Resonance} from './resonance.js'
import {avatarStateFor,activityAdornment} from './avatar-state.js'
import {bindSecretDoor} from './secret-door.js'
export function createLivingSky(adapter){
 const {state,QA,app,shell,renderHome,renderBaseHome,avatarVisual,ambient,travel,toast}=adapter
 let stars=[],events=[],definitions=CONSTELLATIONS,loadedPlayer=null,film=null,atlas=null,remote=null,preview=false,poll=null,storyFilm=null,globalPauseAt=null,initialize=null,initialized=false
 const lang=()=>state.lang||'es',me=()=>state.profile?.player_key||'carlos',mode=()=>engine.get(),paused=()=>document.hidden||state.discreet||mode().status!=='normal'
 const sanctuary=new Sanctuary({onColor:()=>adapter.colorChanged?.(),url:adapter.url,key:adapter.key,onState:value=>{remote=value;engine.sync(value);applyMode();sleep();refresh();},onPreview:id=>id==='roses'?privateRosePreview():alignment(true),onClose:()=>{if(state.profile)renderHome()}})
 function privateRosePreview(){const layer=document.createElement('section');layer.className='sanctuary-preview-layer';document.body.append(layer);layer.addEventListener('click',e=>{if(e.target.closest('[data-action="home"]'))layer.remove()});new RoseGarden({app:layer,shell:html=>`<main class="main-wrap">${html}</main>`,lang:lang(),preview:true,avatarMarkup:`<span class="birthday-avatar-wrap">${avatarVisual(state.profile?.avatar_id||'cow-reader','full','kora')}${['birthday-alignment','birthday-afterglow'].includes(mode().mode)?'':birthdayAdornment('kora')}</span>`}).render()}
 const resonance=new Resonance({lang,enabled:()=>mode().effects&&!paused(),navigate:(destination,msg)=>{if(destination==='atlas')return openAtlas();if(destination==='room'&&msg.metadata?.room_code)return adapter.joinRoom(msg.metadata.room_code);if(destination==='coffee')return adapter.coffee();travel(destination==='room'?'shared':destination)}})
 function applyMode(){const value=mode();if(value.status!=='normal'&&!globalPauseAt)globalPauseAt=Date.now();if(value.status==='normal'&&globalPauseAt){const delta=Date.now()-globalPauseAt;if(state.invaders?.end)state.invaders.end+=delta;if(state.chaos?.end)state.chaos.end+=delta;globalPauseAt=null}document.documentElement.dataset.universeMode=value.mode;document.documentElement.dataset.skyEffects=String(value.effects);document.documentElement.dataset.universeStatus=value.status;ambient.pause?.(paused());}
 function sleep(){let layer=document.querySelector('#universe-sleep');if(mode().status==='normal'){layer?.remove();return}if(!layer){layer=document.createElement('section');layer.id='universe-sleep';layer.className='universe-sleep';layer.innerHTML=`<p>${lang()==='en'?'The universe is resting.':'El universo está descansando.'}</p><button class="sanctuary-star" aria-label="Estrella">✦</button>`;document.body.append(layer)}bindHold(layer.querySelector('button'),true)}
 function bindHold(button,sleeping=false){bindSecretDoor(button,{allowed:()=>!QA.active&&(sleeping||me()==='carlos'),onOpen:()=>sanctuary.open(),onHolding:value=>document.documentElement.classList.toggle('sanctuary-holding',value)})}
 async function refresh(){if(QA.active||preview)return;try{const previous=mode().mode;const response=await fetch(`/api/sky?player=${me()}`,{signal:AbortSignal.timeout(10000)});if(!response.ok)return;const value=await response.json();if(QA.active||preview)return;remote=value.state;engine.sync(value.state,value.server_time);stars=mergeStars(stars,value.stars||[]);events=value.events||[];definitions=value.definitions?.length?value.definitions:CONSTELLATIONS;loadedPlayer=state.profile?me():null;applyMode();sleep();if(initialize&&!initialized&&mode().status==='normal'){initialized=true;await initialize()}else if(state.screen==='home'&&state.profile&&previous!==mode().mode&&!film&&!sanctuary.overlay)enterHome();if(state.screen==='atlas'&&atlas)atlas.setStars(stars)}catch{/* Existing V5 remains usable if the expansion backend is unavailable. */}}
 async function save(action,data={}){if(QA.active||preview||mode().preview)throw Error('Preview');const response=await fetch('/api/sky',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({player:me(),action,...data})});const value=await response.json();if(!response.ok)throw Error(value.error);if(value.star)stars=mergeStars(stars,[{...value.star,id:`${value.star.player_key}:${value.star.event_key}`}]);if(value.progress){events=events.filter(e=>e.event_id!==BIRTHDAY.id);events.push(value.progress)}return value}
 function adornment(player=me(),size='md'){const value=mode();return ['birthday-alignment','birthday-afterglow'].includes(value.mode)?birthdayAdornment(player,size):value.mode==='birthday-prelude'?birthdayAdornment(player,size,true):''}
 function decorations(world){return `${mode().mode==='birthday-prelude'&&mode().effects?'<div class="prelude-dust" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>':''}${world==='home'&&state.screen==='home'&&me()==='carlos'&&!QA.active?'<button class="sanctuary-star home-secret-star" aria-label="Estrella">✦</button>':''}`}
 function homeMarkup(){const value=mode(),en=lang()==='en';let content='';if(value.mode==='birthday-prelude')content=`<p class="sky-hint">${BIRTHDAY.prelude[lang()][Math.floor(Date.now()/86400000)%3]}</p>`;if(['birthday-alignment','birthday-afterglow'].includes(value.mode))content=`<section class="birthday-arrival"><small>10 · 10 · 2026</small><h2>${value.mode==='birthday-alignment'?BIRTHDAY.greeting[lang()]:BIRTHDAY.afterglow[lang()]}</h2><p>${BIRTHDAY.narrative[lang()]}</p><button class="quiet-link" data-action="sky-roses">${en?'Ten roses':'Diez rosas'} ↗</button><button class="quiet-link" data-action="sky-replay">${en?'Relive my alignment':'Revivir mi alineación'} ↗</button><button class="quiet-link" data-action="sky-original-replay">${en?'Original 10/10 celebration':'Celebración original 10/10'} ↗</button></section>`;return `${content}<section class="atlas-gateway"><span aria-hidden="true">✦ ─ · ─ ✧</span><div><small>${en?'CELESTIAL ATLAS':'ATLAS CELESTE'}</small><h2>${en?'What we lived stays in the sky.':'Lo vivido se queda en el cielo.'}</h2></div><button class="quiet-link" data-action="sky-atlas">${en?'Read our sky':'Leer nuestro cielo'} ↗</button></section>`}
 async function enterHome(){applyMode();sleep();if(loadedPlayer!==me())await refresh();const value=mode(),receipt=events.find(e=>e.event_id===BIRTHDAY.id);if(value.mode==='birthday-alignment'&&me()==='kora'&&!receipt?.completed_at&&!value.preview&&!QA.active){renderBaseHome();return alignment(false)}renderBaseHome()}
 function alignment(replay=true){if(film)return;const isPreview=QA.active||preview||mode().preview;film=mountAlignment({lang:lang(),avatarMarkup:`<span class="birthday-avatar-wrap">${avatarVisual(state.profile?.avatar_id||'cow-reader','full','kora')}${['birthday-alignment','birthday-afterglow'].includes(mode().mode)?'':birthdayAdornment('kora')}</span>`,ambient,replay:replay||isPreview,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches||!mode().effects||document.documentElement.dataset.quality==='low',paused:()=>document.hidden||state.discreet||(!replay&&paused()),onComplete:async()=>{film=null;if(!replay&&!isPreview){try{await save('alignment_complete');}catch{toast(lang()==='en'?'This arrival could not be saved. You can retry from home.':'No pudimos guardar esta llegada. Puedes volver a intentarlo desde inicio.')}}renderBaseHome()},onExit:()=>{film=null;renderBaseHome()}})}
 function story(startScene=null,birthYear){if(storyFilm||film)return;storyFilm=mountAlignmentStory({lang:lang(),ambient,startScene,birthYear,prophecy:startScene==='prophecy',low:document.documentElement.dataset.quality==='low',externalPause:()=>state.discreet,onExit:()=>{storyFilm=null}})}
 function roses(forcePreview=false){state.screen='roses';adapter.clearTimers();const receipt=events.find(e=>e.event_id===BIRTHDAY.id);new RoseGarden({app,shell,lang:lang(),preview:forcePreview||QA.active||preview||mode().preview||!['birthday-alignment','birthday-afterglow'].includes(mode().mode),opened:receipt?.roses||[],avatarMarkup:avatarVisual(state.profile?.avatar_id||'cow-reader','full'),onOpen:rose=>save('rose_open',{rose})}).render()}
 function demoStars(){return [{id:'demo-aurelia',player_key:'kora',event_key:'demo-aurelia',title:'La Alineación 10/10',star_name:'Aurelia',event_date:BIRTHDAY.date,event_type:'alignment',story:BIRTHDAY.starStory[lang()],fragment:BIRTHDAY.fragment[lang()],metadata:{constellation:'rosa-decem',replay:'alignment',gold:true}},{id:'demo-coffee',player_key:'carlos',event_key:'demo-coffee',title:'Un café compartido',star_name:'Una pausa',event_date:'2026-10-09',event_type:'coffee',story:'Dos luces hicieron una pausa.',fragment:'Todo podía esperar.',metadata:{constellation:'coffee'}}]}
 function openAtlas(demo=false){state.screen='atlas';adapter.clearTimers();stars=mergeStars((adapter.localStars()||[]).map(legacyStar),stars);atlas=new CelestialAtlas({app,shell,lang:lang(),stars:demo?demoStars():stars,definitions,preview:demo,prelude:mode().mode==='birthday-prelude',onReplay:()=>story(),onStory:scene=>story(scene),onBirthdayReplay:()=>alignment(true)});atlas.render();if(!demo)refresh()}
 function qaMarkup(){return `<section class="sky-qa-controls"><h2>The Living Sky · vistas sin guardar</h2>${[['classic','Classic'],['birthday-prelude','Prelude'],['birthday-alignment','Alignment'],['birthday-afterglow','Afterglow'],['avatar','Avatar cumpleaños'],['roses','Diez rosas'],['atlas','Atlas de prueba'],['cow','Vaca-Señal'],['kora','KORA-Señal'],['story','Alignment Story'],['story-arrival','03/10/2025'],['story-recognition','≈ 12/10/2025'],['story-rose','Rosa única'],['story-prophecy','Profecía 2027'],['story-birth-null','Nacimiento sin año'],['story-birth-preview','Simular año confirmado']].map(([id,label])=>`<button class="btn-v3 soft" data-action="sky-qa" data-preview="${id}">${label}</button>`).join('')}<label>Año de nacimiento solo para QA<input id="qaStoryBirthYear" type="number" min="2001" max="2026" placeholder="Sin definir"></label></section>`}
 function qaPreview(id){if(!QA.active)return;preview=true;if(id.startsWith('story')){const scene={"story-arrival":'arrival',"story-recognition":'recognition',"story-rose":'unique-rose',"story-prophecy":'prophecy',"story-birth-null":'new-light',"story-birth-preview":'new-light'}[id];const year=id==='story-birth-preview'?Number(app.querySelector('#qaStoryBirthYear')?.value):null;if(id==='story-birth-preview'&&(!Number.isInteger(year)||year<2001||year>new Date().getFullYear()))return toast('Introduce un año confirmado solo para la simulación.');return story(scene,year)}if(['classic','birthday-prelude','birthday-alignment','birthday-afterglow'].includes(id)){engine.setOverride({mode:id,preview:true,event_id:BIRTHDAY.id});applyMode();if(id==='birthday-alignment')alignment(true);else renderBaseHome()}else if(id==='roses')roses(true);else if(id==='atlas')openAtlas(true);else if(id==='avatar'){engine.setOverride({mode:'birthday-alignment',preview:true});applyMode();renderBaseHome()}else resonance.receive({id:crypto.randomUUID(),kind:id==='kora'?'coffee_invite':'text'},{preview:true})}
 app.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;if(b.dataset.action==='sky-atlas')openAtlas();if(b.dataset.action==='sky-roses')roses();if(b.dataset.action==='sky-replay')story();if(b.dataset.action==='sky-original-replay')alignment(true);if(b.dataset.action==='sky-qa')qaPreview(b.dataset.preview)})
 new MutationObserver(()=>{bindHold(app.querySelector('.home-secret-star'));app.querySelectorAll('.avatar-visual').forEach(el=>{const next=avatarStateFor({screen:state.screen,mode:mode().mode,status:mode().status});el.dataset.avatarState=next;const prop=el.querySelector('.avatar-state-prop');if(prop?.dataset.prop!==next){prop?.remove();const markup=activityAdornment(next);if(markup)el.insertAdjacentHTML('beforeend',markup)}})}).observe(app,{childList:true,subtree:true})
 document.addEventListener('visibilitychange',()=>{if(!document.hidden){applyMode();refresh()}})
 return {adornment,decorations,homeMarkup,enterHome,qaMarkup,openAtlas,roses,alignment,
  receive:msg=>resonance.receive(msg),wave:()=>resonance.quietWave(adapter.partnerPresence(),state.screen),
  captureLegacy:row=>{stars=mergeStars(stars,[legacyStar(row)]);if(!QA.active)save('milestone',{key:row.event_key}).catch(()=>{})},
  restoreQA:()=>{preview=false;engine.sync(remote);applyMode();refresh()},
  start:async init=>{await refresh();applyMode();initialize=init;if(mode().status==='normal'){initialized=true;await init()}poll=setInterval(()=>{refresh();resonance.quietWave(adapter.partnerPresence(),state.screen)},30000);window.addEventListener('pagehide',()=>clearInterval(poll))}
 }
}
