// Development-only visual laboratory. Not part of the production build or Auth QA.
import './style.css'
import './v5.css'
import './living-sky.css'
import {BIRTHDAY,CONSTELLATIONS} from './birthday-data.js'
import {mountAlignment,RoseGarden,birthdayAdornment} from './birthday-experience.js'
import {CelestialAtlas} from './atlas.js'
import {universeEngine} from './universe-engine.js'
import {Sanctuary} from './sanctuary.js'
import {unlockVault,encode64} from './sanctuary-crypto.js'
if(!import.meta.env.DEV)throw Error('Development preview only')
const app=document.querySelector('#app'),controls=document.querySelector('#preview-controls')
const avatar=`<span class="avatar-visual full" style="--avatar-accent:#d5b88d"><img src="/avatars/cow-classic.svg" alt="Kora"><span class="avatar-fallback">🐮</span>${birthdayAdornment('kora')}</span>`
const shell=html=>`<main class="main-wrap">${html}</main>`
controls.innerHTML=`<nav class="sky-qa-controls" style="padding:1rem;position:relative;z-index:10"><span>Vista local · no guarda nada</span>${['classic','birthday-prelude','birthday-alignment','birthday-afterglow','roses','atlas','sleep','book'].map(id=>`<button class="btn-v3 soft" data-view="${id}">${id}</button>`).join('')}</nav>`
controls.addEventListener('click',async e=>{if(e.target.closest('[data-view]')?.dataset.view!=='book')return;const book=new Sanctuary({onState:()=>{},onPreview:()=>{},onClose:()=>{}}),encrypted=[];book.request=async(resource,method='GET',body)=>{if(resource==='universe')return {status:'normal',mode_override:null,effects_enabled:true};if(method==='POST')encrypted.push(body);return {entries:encrypted}};book.open();book.root=await unlockVault('development-only-test-key',encode64(crypto.getRandomValues(new Uint8Array(32))));book.owner=crypto.randomUUID();book.universe={status:'normal',mode_override:null,effects_enabled:true};book.entries=[{id:crypto.randomUUID(),section:'diary',title:'Una página de prueba',body:'Esta página pertenece a la vista de desarrollo. No contiene palabras del diario real.',tags:['prueba'],date:'2026-10-07'}];book.selected=book.entries[0].id;book.render('Vista de desarrollo: datos simulados, sin conexión al Santuario real.')})
function home(mode){document.documentElement.dataset.universeMode=mode;app.innerHTML=shell(`<section class="birthday-arrival"><small>${mode}</small><h1>Un cielo a su ritmo.</h1><div class="rose-garden-avatar">${mode==='classic'?'🐮':avatar}</div><p>${mode==='birthday-prelude'?BIRTHDAY.prelude.es[0]:mode==='birthday-afterglow'?BIRTHDAY.afterglow.es:BIRTHDAY.narrative.es}</p></section>`)}
controls.addEventListener('click',e=>{const id=e.target.closest('[data-view]')?.dataset.view;if(!id||id==='book')return;document.querySelector('.universe-sleep')?.remove();if(id==='roses')return new RoseGarden({app,shell,preview:true,avatarMarkup:avatar}).render();if(id==='atlas')return new CelestialAtlas({app,shell,preview:true,definitions:CONSTELLATIONS,stars:[{id:'aurelia',player_key:'kora',event_key:'alignment-2026',title:'La Alineación 10/10',star_name:'Aurelia',event_date:BIRTHDAY.date,event_type:'alignment',story:BIRTHDAY.starStory.es,fragment:BIRTHDAY.fragment.es,metadata:{constellation:'rosa-decem',replay:'alignment'}},{id:'roses',player_key:'kora',event_key:'ten-roses',title:'Diez rosas',star_name:'Rosa Decem',event_date:BIRTHDAY.date,event_type:'roses',story:'Diez formas de mirar una luz.',fragment:'Y después estás tú.',metadata:{constellation:'rosa-decem'}}],onReplay:()=>mountAlignment({avatarMarkup:avatar,replay:true})}).render();if(id==='sleep'){const layer=document.createElement('div');layer.className='universe-sleep';layer.innerHTML='<p>El universo está descansando.</p><button class="sanctuary-star" aria-label="Despertar la vista de prueba">✦</button>';layer.querySelector('button').onclick=()=>layer.remove();document.body.append(layer);return}universeEngine.setOverride({mode:id,preview:true});home(id);if(id==='birthday-alignment')mountAlignment({avatarMarkup:avatar,replay:true})})
home('classic')
