import {createClient} from '@supabase/supabase-js'
import {unlockVault,encryptEntry,decryptEntry} from './sanctuary-crypto.js'
import {escapeHTML as esc} from './sky-utils.js'
import {ORIGIN_CHAPTERS} from './birthday-data.js'
export class Sanctuary{
 constructor({onState,onPreview,onClose,url,key}){Object.assign(this,{onState,onPreview,onClose,url,key});this.root=null;this.entries=[];this.section='diary';this.selected=null;this.owner=null;this.timer=null;this.overlay=null;this.universe=null;this.hidden=()=>{if(document.hidden)this.lock()};document.addEventListener('visibilitychange',this.hidden);window.addEventListener('pagehide',()=>this.lock())}
 async request(resource,method='GET',body){const response=await fetch(`/api/sanctuary?resource=${resource}`,{method,credentials:'same-origin',headers:method==='GET'?{}:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const value=await response.json();if(!response.ok)throw Error(value.error||'La puerta se ha cerrado.');return value}
 touch(){clearTimeout(this.timer);this.timer=setTimeout(()=>this.lock(),5*60*1000)}
 open(){if(this.overlay)return;this.generation=(this.generation||0)+1;this.previousInert=document.querySelector('#app')?.inert;if(document.querySelector('#app'))document.querySelector('#app').inert=true;this.overlay=document.createElement('section');this.overlay.className='sanctuary-overlay';this.overlay.setAttribute('role','dialog');this.overlay.setAttribute('aria-modal','true');this.overlay.setAttribute('aria-label','El Santuario');document.body.append(this.overlay);this.overlay.addEventListener('input',()=>this.touch());this.overlay.addEventListener('pointerdown',()=>this.touch());this.unlockForm()}
 unlockForm(message=''){
  this.overlay.innerHTML=`<div class="sanctuary-door"><button class="sanctuary-close" aria-label="Cerrar">×</button><span class="sanctuary-glyph">✦</span><p class="eyebrow">Hay lugares que no necesitan testigos.</p><h1>El Santuario</h1><p>Solo tú conoces la llave.</p><form id="sanctuary-unlock"><label>Tu cuenta<input name="email" type="email" autocomplete="username" required></label><label>Contraseña de tu cuenta<input name="password" type="password" autocomplete="current-password" required></label><label>La llave privada<input name="pin" type="password" autocomplete="off" minlength="8" maxlength="128" required></label><button type="submit" class="btn primary">Abrir este lugar</button><p role="status">${esc(message)}</p></form></div>`
  this.overlay.querySelector('.sanctuary-close').onclick=()=>this.lock()
  this.overlay.querySelector('form').onsubmit=async e=>{
   e.preventDefault();const form=e.currentTarget,button=form.querySelector('button');button.disabled=true
   let auth,pin=form.elements.pin.value;const generation=this.generation
   try{
    if(!this.url||!this.key)throw Error('Este lugar todavía no está configurado.')
    auth=createClient(this.url,this.key,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}})
    const signed=await auth.auth.signInWithPassword({email:form.elements.email.value,password:form.elements.password.value})
    form.elements.password.value=''
    if(signed.error)throw Error('No se pudo abrir este lugar.')
    const response=await fetch('/api/sanctuary-unlock',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json',Authorization:`Bearer ${signed.data.session.access_token}`},body:JSON.stringify({pin})})
    const vault=await response.json();if(!response.ok)throw Error(vault.error)
    const root=await unlockVault(pin,vault.salt);pin='';form.elements.pin.value='';if(generation!==this.generation||!this.overlay){await this.request('session','DELETE');return}
    this.root=root;this.owner=vault.owner
    const encrypted=(await this.request('entries')).entries
    const entries=await Promise.all(encrypted.map(async row=>({id:row.id,...await decryptEntry(root,vault.owner,row)})))
    const universe=await this.request('universe');if(generation!==this.generation||!this.overlay)return
    this.entries=entries;this.universe=universe;clearTimeout(this.expiryTimer);this.expiryTimer=setTimeout(()=>this.lock(),Math.max(0,vault.expires_at-Date.now()));this.touch();this.render()
   }catch(error){this.root=null;this.entries=[];if(this.overlay)this.unlockForm(error.message||'La puerta no se abrió.')}
   finally{pin='';if(auth)await auth.auth.signOut()}
  };this.overlay.querySelector('input').focus()
 }
 render(message=''){
  if(!this.root)return;this.touch()
  const names={diary:'Diario',origin:'Origin',letters:'Cartas que nunca envié',confessions:'Confesiones',machine:'El universo'}
  const rows=this.entries.filter(e=>e.section===this.section).sort((a,b)=>(a.order||0)-(b.order||0)||a.date.localeCompare(b.date))
  const current=this.entries.find(e=>e.id===this.selected)
  this.overlay.innerHTML=`<div class="sanctuary-book"><header><span class="eyebrow">Un lugar fuera de las órbitas</span><h1>El Santuario</h1><button class="sanctuary-close btn">Cerrar la puerta</button></header><nav>${Object.entries(names).map(([id,name])=>`<button data-section="${id}" class="${this.section===id?'active':''}">${name}</button>`).join('')}</nav><p role="status" id="sanctuary-status">${esc(message)}</p>${this.section==='machine'?this.machineMarkup():`<div class="sanctuary-pages"><aside><label>Buscar entre estas páginas<input id="diary-search" placeholder="Título, fecha o etiqueta"></label><button id="diary-new" class="btn">${this.section==='confessions'?'Confesar algo':'Una página nueva'}</button>${this.section==='origin'?'<button id="origin-seed" class="btn">Preparar el manuscrito</button>':''}<div class="diary-index">${rows.map(e=>`<button data-entry="${e.id}" data-search="${esc(`${e.title} ${e.date} ${(e.tags||[]).join(' ')}`.toLowerCase())}"><span>${esc(e.title||'Sin título')}</span><small>${esc(e.date)}${e.status?` · ${esc(e.status)}`:''}</small></button>`).join('')||'<p>Este silencio todavía no tiene palabras.</p>'}</div></aside><article>${this.editorMarkup(current)}</article></div>`}</div>`
  this.overlay.querySelector('.sanctuary-close').onclick=()=>this.lock()
  this.overlay.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{this.section=b.dataset.section;this.selected=null;this.render()})
  if(this.section==='machine')return this.bindMachine()
  this.overlay.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>{this.selected=b.dataset.entry;this.render()})
  this.overlay.querySelector('#diary-search').oninput=e=>this.overlay.querySelectorAll('[data-entry]').forEach(b=>b.hidden=!b.dataset.search.includes(e.target.value.toLowerCase()))
  this.overlay.querySelector('#diary-new').onclick=()=>{this.selected=null;this.render();this.overlay.querySelector('[name=title]').focus()}
  const seed=this.overlay.querySelector('#origin-seed');if(seed)seed.onclick=async()=>{seed.disabled=true;try{for(let i=0;i<ORIGIN_CHAPTERS.length;i++)if(!this.entries.some(e=>e.section==='origin'&&e.chapter===i+1))await this.save({id:crypto.randomUUID(),section:'origin',chapter:i+1,title:ORIGIN_CHAPTERS[i],body:'',tags:[],date:new Date().toISOString().slice(0,10),order:i+1});this.render('El manuscrito está preparado.')}catch(e){this.render(e.message)}}
  const editor=this.overlay.querySelector('#diary-editor');editor.onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;f.querySelector('[type=submit]').disabled=true;try{await this.save({id:current?.id||crypto.randomUUID(),chapter:current?.chapter,section:this.section,title:f.elements.title.value,body:f.elements.body.value,date:f.elements.date.value,tags:f.elements.tags.value.split(',').map(t=>t.trim()).filter(Boolean),status:f.elements.status?.value||'',order:Number(f.elements.order?.value||0)});this.render('Estas palabras están guardadas.')}catch(e){if(this.overlay){this.overlay.querySelector('#sanctuary-status').textContent=e.message;f.querySelector('[type=submit]').disabled=false}}}
  const remove=this.overlay.querySelector('#diary-delete');if(remove)remove.onclick=()=>{remove.textContent='Borrar esta página definitivamente';remove.onclick=async()=>{try{await this.request('entries','DELETE',{id:current.id});this.entries=this.entries.filter(e=>e.id!==current.id);this.selected=null;this.render('La página se ha retirado.')}catch(e){this.render(e.message)}}}
 }
 editorMarkup(entry){return `<form id="diary-editor"><label>Título<input name="title" maxlength="200" value="${esc(entry?.title||'')}" required></label><div class="diary-meta"><label>Fecha<input name="date" type="date" value="${esc(entry?.date||new Date().toISOString().slice(0,10))}" required></label><label>Etiquetas<input name="tags" value="${esc((entry?.tags||[]).join(', '))}" placeholder="Separadas por comas"></label>${this.section==='origin'?`<label>Orden<input name="order" type="number" min="1" value="${entry?.order||1}"></label>`:''}${this.section==='letters'?`<label>Estado<select name="status">${['Borrador','No enviar','Tal vez algún día','Terminada'].map(s=>`<option ${entry?.status===s?'selected':''}>${s}</option>`).join('')}</select></label>`:''}</div><label class="sr-only" for="private-body">Tus palabras</label><textarea id="private-body" name="body" maxlength="50000" placeholder="Aquí puedes escribir sin explicar nada…">${esc(entry?.body||'')}</textarea><footer><button type="submit" class="btn primary">Guardar estas palabras</button>${entry?'<button type="button" id="diary-delete" class="btn">Retirar esta página</button>':''}</footer></form>`}
 async save(value){const generation=this.generation,envelope=await encryptEntry(this.root,this.owner,value.id,value);await this.request('entries','POST',envelope);if(generation!==this.generation||!this.root)throw Error('La puerta se ha cerrado.');const index=this.entries.findIndex(e=>e.id===value.id);if(index<0)this.entries.push(value);else this.entries[index]=value;this.selected=value.id}
 machineMarkup(){const u=this.universe;return `<article class="sanctuary-machine"><h2>El cielo también necesita descansar.</h2><label>Estado<select id="universe-status"><option value="normal" ${u.status==='normal'?'selected':''}>Despierto</option><option value="paused" ${u.status==='paused'?'selected':''}>En pausa</option><option value="maintenance" ${u.status==='maintenance'?'selected':''}>Descansando</option></select></label><label>La estación del cielo<select id="universe-mode">${[['auto','Automático'],['classic','Classic'],['birthday-prelude','Prelude'],['birthday-alignment','Alignment'],['birthday-afterglow','Afterglow']].map(([id,name])=>`<option value="${id}" ${(u.mode_override?.mode||'auto')===id?'selected':''}>${name}</option>`).join('')}</select></label><label><input type="checkbox" id="universe-preview" ${u.mode_override?.preview!==false?'checked':''}> Vista previa: no crear recuerdos del cumpleaños</label><label><input type="checkbox" id="universe-effects" ${u.effects_enabled?'checked':''}> Efectos suaves del cielo</label><div class="sanctuary-control-actions"><button id="universe-save" class="btn primary">Guardar el estado del cielo</button><button id="universe-restore" class="btn">Restaurar Classic y despertar</button><button id="universe-preview-kora" class="btn">Ver la llegada de Kora</button><button id="universe-preview-roses" class="btn">Ver las diez rosas</button></div><p>Las vistas previas no guardan progreso. El modo automático sigue la hora de Santo Domingo. Las palabras del cumpleaños se editan en birthday-data.js.</p></article>`}
 bindMachine(){this.overlay.querySelector('#universe-preview-kora').onclick=()=>this.onPreview('alignment');this.overlay.querySelector('#universe-preview-roses').onclick=()=>this.onPreview('roses');const save=async restore=>{try{const mode=this.overlay.querySelector('#universe-mode').value;const state=restore?{status:'normal',mode_override:{mode:'classic',preview:true},effects_enabled:true}:{status:this.overlay.querySelector('#universe-status').value,mode_override:mode==='auto'?null:{mode,preview:this.overlay.querySelector('#universe-preview').checked,event_id:'alignment-2026'},effects_enabled:this.overlay.querySelector('#universe-effects').checked};this.universe=await this.request('universe','POST',state);this.onState(this.universe);this.render('El cielo ha encontrado su ritmo.')}catch(e){this.render(e.message)}};this.overlay.querySelector('#universe-save').onclick=()=>save(false);this.overlay.querySelector('#universe-restore').onclick=()=>save(true)}
 lock(){this.generation=(this.generation||0)+1;clearTimeout(this.timer);clearTimeout(this.expiryTimer);this.root=null;this.owner=null;this.entries=[];this.selected=null;document.querySelector('.sanctuary-preview-layer')?.remove();if(this.overlay){this.overlay.replaceChildren();this.overlay.remove();this.overlay=null;if(document.querySelector('#app'))document.querySelector('#app').inert=Boolean(this.previousInert);this.request('session','DELETE').catch(()=>{});this.onClose?.()}}
}
