import { CONSTELLATIONS } from './birthday-data.js'
export const escapeHTML=(value='')=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
export function validDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const d=new Date(value+'T12:00:00Z');return !isNaN(d)&&d.toISOString().slice(0,10)===value}
export function stepDate(value,days){const d=new Date(value+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
export function mergeStars(current,incoming){const result=new Map();for(const star of [...current,...incoming]){const id=`${star.player_key||'shared'}:${star.event_key}`;result.set(id,{...star,id})}return [...result.values()].sort((a,b)=>a.event_date.localeCompare(b.event_date)||a.event_key.localeCompare(b.event_key))}
export function starsForDate(stars,date,{timeTravel=false}={}){if(!validDate(date))return [];return stars.filter(s=>timeTravel?s.event_date<=date:s.event_date===date)}
export function constellationFor(star,definitions=CONSTELLATIONS){return star.metadata?.constellation||definitions.find(c=>c.types.includes(star.event_type))?.id||'first-encounter'}
export function classifySignal(message){if(message.kind==='sketch')return 'sketch';if(['coffee_invite','coffee_reply'].includes(message.kind))return 'coffee_invite';if(['game_invite','invite'].includes(message.kind))return 'game_invite';if(message.kind==='system_event')return 'system_event';return 'text'}
export function signalDestination(message){const type=classifySignal(message);if(type==='coffee_invite')return 'coffee';if(type==='game_invite')return message.metadata?.room_code?'room':'shared';if(type==='sketch'||type==='text')return 'signals';return 'atlas'}
export function legacyStar(row){const key=row.event_key||'';const type=key.includes('coffee')?'coffee':key.includes('sketch')?'sketch':key.includes('check')||key.includes('chess')?'chess':key.includes('sudoku')?'sudoku':key.includes('duo')?'duo':key.includes('english')?'learning':key.includes('puzzle')||key.includes('arcade')||key.includes('trivia')?'game':key.includes('signal')?'signal':'visit';return {...row,id:row.id||'legacy:'+row.player_key+':'+key,title:row.label||row.title||'Una pequeña luz',star_name:row.star_name||row.label||'Una pequeña luz',event_date:row.event_date||new Intl.DateTimeFormat('en-CA',{timeZone:'America/Santo_Domingo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(row.created_at)),event_type:type,story:row.story||row.label||'',fragment:row.fragment||'Lo vivido también ilumina.',visibility:'shared',metadata:{...row.metadata,legacy:true}}}
export function starPosition(star,definitions=CONSTELLATIONS){if(Array.isArray(star.metadata?.coordinates))return star.metadata.coordinates;const c=definitions.find(c=>c.id===constellationFor(star,definitions))||definitions[0];let hash=0;for(const char of `${star.player_key}:${star.event_key}`)hash=(hash*31+char.charCodeAt(0))>>>0;return [Math.max(8,Math.min(92,c.anchor[0]+((hash%1700)/100)-8.5)),Math.max(10,Math.min(90,c.anchor[1]+(((hash>>4)%1500)/100)-7.5))]}
export function roseSVG(gold=false){return `<svg viewBox="0 0 100 130" aria-hidden="true" class="rose-art ${gold?'gold':''}"><path class="rose-stem" d="M50 55 C42 76 59 92 48 126 M49 94 C20 95 22 79 44 84 M51 109 C76 108 78 92 55 100"/><g class="rose-petals"><path d="M50 18 C27 4 12 27 24 49 C15 68 40 79 50 69 C66 81 87 63 77 47 C91 25 69 6 50 18Z"/><path d="M50 22 C27 17 22 41 38 53 C26 63 51 73 61 57 C78 61 81 33 60 30Z"/><path d="M50 29 C33 29 32 48 50 50 C67 52 69 34 50 29Z M42 37 Q51 30 60 41 Q51 47 42 37"/></g></svg>`}
