// Development-only, isolated fixtures. No Supabase, Auth, uploads, push or saved rewards.
import './style.css'
import './v5.css'
import './living-sky.css'
import './signals.css'
import {renderMessage} from './signals-renderers.js'
import {typingMarkup} from './signals-utils.js'
import {mountPinKeypad} from './sanctuary-pin.js'
import {openPhotoLightbox,preparePhoto} from './chat-media.js'
import {triviaQueue} from './trivia-session.js'
const app=document.querySelector('#app'),queue=triviaQueue('mix');let index=0
const meta={path:'kora/2026/10/11111111-1111-4111-8111-111111111111.webp',width:800,height:600}
const avatar='<img src="/avatars/cow-galaxy.svg" alt="Kora" width="36" height="36">'
app.innerHTML=`<main style="padding:2rem;max-width:600px"><small>MUESTRA LOCAL · SIN CONEXIÓN</small><h1>Signals 2.0</h1><p>Una frase, una imagen, una partida. Esta muestra no envía mensajes ni guarda datos.</p><div class="social-qa-actions"><button id="quote">Frase</button><button id="photo">Foto simulada</button><button id="expired">Sala cerrada</button><button id="typing">Escritura</button><button id="pin">Teclado PIN</button><button id="trivia">Trivia 20</button><button id="open">Abrir chat</button></div><section id="triviaPreview"></section><p id="previewResult" role="status"></p></main><aside class="social-panel open" id="socialPanel"><header class="social-head"><div class="social-person">${avatar}<div><b>Kora</b><small>En la misma órbita · muestra</small></div></div><div class="chat-head-actions"><button id="gallery" aria-label="Historial multimedia">▧</button><button id="close" aria-label="Cerrar chat">×</button></div></header><p class="chat-connection">Muestra aislada · ninguna señal sale de aquí</p><div class="social-quick"><button id="chess">♟ Ajedrez</button><button id="sudoku">🧩 Sudoku</button><button id="inviteTrivia">✦ Trivia</button></div><div class="social-messages" id="socialMessages"></div><div class="typing-line" id="typingLine">${typingMarkup('Kora',avatar,'es')}</div><div class="chat-compose"><button id="attach" aria-label="Adjuntar fotografía">+</button><input type="file" hidden id="previewPhoto" accept="image/jpeg,image/png,image/webp,image/heic,image/heif"><input id="chatInput" aria-label="Escribe un mensaje" placeholder="Escribe un mensaje…"><button id="send" aria-label="Enviar">↑</button></div></aside>`
const messages=document.querySelector('#socialMessages'),panel=document.querySelector('#socialPanel');let count=0
function add(kind,body,metadata={},status){const id=String(++count);messages.insertAdjacentHTML('beforeend',renderMessage({id,kind,body,metadata,from_player:'kora'},{me:'carlos',status}));messages.scrollTop=messages.scrollHeight;return id}
function invite(game,status){add('game_invite','Kora te invita a compartir una órbita.',{room_code:'ABC123',game},status)}
document.querySelector('#quote').onclick=()=>add('quote','No todo minuto libre tiene que convertirse en productividad.',{source:'quiet-library'})
document.querySelector('#photo').onclick=()=>{const id=add('photo','Una pequeña vaca cruzó el cielo.',meta);const img=messages.querySelector(`[data-message-id="${id}"] img`);img.src='/avatars/cow-galaxy.svg';img.parentElement.querySelector('span').hidden=true;img.parentElement.onclick=()=>openPhotoLightbox('/avatars/cow-galaxy.svg','Una imagen simulada','es')}
document.querySelector('#expired').onclick=()=>invite('trivia','closed')
document.querySelector('#typing').onclick=()=>{document.querySelector('#typingLine').classList.add('show');setTimeout(()=>document.querySelector('#typingLine').classList.remove('show'),4000)}
document.querySelector('#pin').onclick=()=>{const box=document.createElement('div');box.className='sanctuary-overlay';box.tabIndex=-1;box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');document.body.appendChild(box);mountPinKeypad(box,{close:()=>box.remove(),submit:async pin=>{if(pin!=='0451')throw Error('wrong');box.innerHTML='<div class="sanctuary-door"><h1>El cielo se abrió</h1><p>Muestra de interfaz · ningún diario fue abierto.</p><button id="done">Cerrar</button></div>';box.querySelector('#done').onclick=()=>box.remove()}})}
document.querySelector('#trivia').onclick=()=>{index=0;panel.classList.remove('open');question()}
function question(){const el=document.querySelector('#triviaPreview'),q=queue[index];if(!q){el.innerHTML='<h2>20 / 20 · partida terminada</h2>';return}el.innerHTML=`<small>Pregunta ${index+1} de 20 · ${q.difficulty}</small><h2>${q.q}</h2>${q.a.map((a,i)=>`<button data-answer="${i}" class="btn-v3 soft">${a}</button>`).join('')}<p id="explain"></p><button id="next" class="btn-v3 signal" disabled>Siguiente</button>`;el.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{el.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);el.querySelector('#explain').textContent=q.explanation;el.querySelector('#next').disabled=false});el.querySelector('#next').onclick=()=>{index++;question()}}
for(const [id,game]of [['chess','chess'],['sudoku','sudoku'],['inviteTrivia','trivia']])document.querySelector('#'+id).onclick=()=>invite(game)
document.querySelector('#close').onclick=()=>panel.classList.remove('open');document.querySelector('#open').onclick=()=>panel.classList.add('open')
document.querySelector('#gallery').onclick=()=>messages.classList.toggle('social-gallery')
document.querySelector('#send').onclick=()=>{const input=document.querySelector('#chatInput');if(input.value.trim())add('text',input.value);input.value=''}
document.querySelector('#attach').onclick=()=>document.querySelector('#previewPhoto').click()
document.querySelector('#previewPhoto').onchange=async e=>{try{const photo=await preparePhoto(e.target.files[0]),url=URL.createObjectURL(photo.blob);add('photo','Imagen preparada localmente, sin subir.',{...meta,width:photo.width,height:photo.height});const img=messages.querySelector('.chat-message:last-child img');img.src=url;img.parentElement.querySelector('span').hidden=true;img.parentElement.onclick=()=>openPhotoLightbox(url,'Prueba local','es');document.querySelector('#previewResult').textContent=`${photo.width} × ${photo.height} · ${Math.round(photo.blob.size/1024)} KB`}catch(error){document.querySelector('#previewResult').textContent=error.message}}
messages.onclick=e=>{const button=e.target.closest('[data-action="join-invite"],[data-action="new-invite"]');if(button){button.closest('article').querySelector('.invite-status').textContent='Entraste a la órbita. · muestra sin conexión'}}
add('text','Llegué. ¿Compartimos un ratito?');document.querySelector('#quote').click();invite('chess')
